### ISSUE TITLE
TCA Configuration partially incorrect (for tx_cetimeline_domain_model_entry)

### ISSUE THREAD

**Issue by format-gmbh** [koehlersimon/ce_timeline#1]
v2.0.2
It affects the entries for searchFields and showRecordFieldList. It should be like this or similar:
`'searchFields' => 'header,description',`
and
`'showRecordFieldList' => 'sys_language_uid, l10n_parent, l10n_diffsource, header, header_layout, description',`

**Comment by koehlersimon** [comment]
Thank you for the hint. I am currently making updates. New release will have all these changes done.
