### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by Epoche-Napoleon** [koehlersimon/ce_timeline#5]
According to the TER, the current bugfix of CE-Timeline version 2.0.3 is designed for core versions 9.5.0 to 10.4.99, whereas a Composer installation only specifies a compactness for 10.x.

**Comment by koehlersimon** [comment]
I have changed the composer settings. Can you check if they now work like expected?
https://packagist.org/packages/simonkoehler/ce-timeline#3.0.0
