### ISSUE TITLE
No timeline_entries can be created

### ISSUE THREAD

**Issue by Epoche-Napoleon** [koehlersimon/ce_timeline#6]
Hello,

i have installed the EXT:ce_timeline 3.01 in a TYPO3 9.5.22 

If I want to create an entry in the timeline (entry_timeline) nothing happens, a hint on error 500 appears in the upper right corner.

The following entry can be found in the TYPO3 log:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1294585866: No class named SIMONKOEHLER\CeTimeline\Userfuncs\Tca | InvalidArgumentException thrown in file /html/epochenapoleon/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3607. Requested URL: https://www.epoche-napoleon.net/typo3/index.php?route=%%2Fajax%%2Frecord%%2Finline%%2Fcreate&token=--AnonymizedToken--

Is this a bug or have I made an error in the configuration?

**Comment by koehlersimon** [comment]
Hey, sorry for the late response. I just updated the Extension so this bug should be history. Might take some time to have it in the TER.
