### ISSUE TITLE
3.01. and 3.20-master and TYPO3 10.4.10

### ISSUE THREAD

**Issue by micha68g** [koehlersimon/ce_timeline#7]
Hi there,

are there any known problems with TYPO3 10.4.10 ?
When I install the extension (either 3.01 or 3.20-master, tested both) and follow the install-instructions no content element of type "Timeline" shows up.

I'm pretty sure, it worked with 10.4.9 on a test-installation. After an upgrade to 10.4.10 you can't see/choose the content element of type "Timeline" anymore.

Or are there maybe any known conflicts with other EXTs  maybe "Mask" or "Static File Cache"?

Greetings
Michael

**Comment by koehlersimon** [comment]
Hmm that's weird. I have it running on my own site with 10.4.10 and 3.0.1 without problems.
I don't use mask or static file cache, sorry so I don't know.

Did you check if all TypoScript configuration is available with the TypoScript browser?
If you like, I can have a look via Skype, too. @medienspezialist

Frontend:
https://simon-koehler.com/produkte/ce-timeline/demo-default-style

Backend:
![Bildschirmfoto 2020-12-08 um 09 52 03](https://user-images.githubusercontent.com/4283692/101499325-244fdf00-393b-11eb-951f-afe17bb972b3.jpg)
![Bildschirmfoto 2020-12-08 um 09 52 19](https://user-images.githubusercontent.com/4283692/101499331-25810c00-393b-11eb-9451-419da5f46af6.jpg)

**Comment by micha68g** [comment]
mh, I tested again. You can't choose a timeline-element from the panel (Screen1), but you can change the CE to timeline if you select another (standard) CE first. (Screen2) 
![screen1_1](https://user-images.githubusercontent.com/52312170/101502064-cb9b3900-3970-11eb-9715-f7451158e75b.png)
![screen2_1](https://user-images.githubusercontent.com/52312170/101502069-cd64fc80-3970-11eb-8acc-4bf2c4ed3cb1.png)

**Comment by koehlersimon** [comment]
Ok the plugin works, only the **Content Element Wizard** is not available. It is not set by default, so you must include this TypoScript in your Page Settings where it is called "Timeline Content Element (ce_timeline)". I would recommend to do it on the root page.

https://github.com/koehlersimon/ce_timeline/blob/54587ecec7b8ffea9b91a8c43082ebc5d6811331/Configuration/TypoScript/TsConfig/page.typoscript

**Comment by koehlersimon** [comment]
I have updated this here, too: https://github.com/koehlersimon/ce_timeline/blob/master/README.md#basic-configuration

**Comment by micha68g** [comment]
well, must have overlook this step. thanks a lot.

BTW: You have a typo in your PayPal-me Link ;-)
One has to remove the "r" in trypo
https://paypal.me/trypo3freelancer/50/ doesn't work 

Greetings Michael

**Comment by koehlersimon** [comment]
Thank you very much, updated it as well! 
Thanks for your support.
